---
# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: false # default is true
contact_links:
  - name: Discussions
    url: https://github.com/redhat-developer/vscode-yaml/discussions
    about: >
      Any kind of questions should go onto discussions.
      We recommend using this even if you suspect a bug or have
      a feature request, so the core team can keep the issue tracker
      clean. Also, note that schema specific bugs should go to their
      repositories as our extension does not contain any schema.
